// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {forward} from '../models';

export function DeletePortForward(arg1:string):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function DeleteSyncMapping(arg1:string):Promise<void>;

export function ExportConfig(arg1:string):Promise<string>;

export function GetLanguage():Promise<string>;

export function GetSyncBackend():Promise<string>;

export function GetTheme():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportConfig(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ListPortForwards():Promise<Array<config.PortForward>>;

export function ListServers():Promise<Array<config.ServerUI>>;

export function ListSyncMappings():Promise<Array<config.SyncMapping>>;

export function OpenConfigDirectory():Promise<void>;

export function OpenLogDirectory():Promise<void>;

export function PortForwardStatus(arg1:string):Promise<forward.Status>;

export function RecentLogs():Promise<Array<string>>;

export function RunFullSync(arg1:string):Promise<Record<string, any>>;

export function SelectLocalDirectory(arg1:string):Promise<string>;

export function SetLanguage(arg1:string):Promise<void>;

export function SetSyncBackend(arg1:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function StartPortForward(arg1:string):Promise<void>;

export function StopPortForward(arg1:string):Promise<void>;

export function TestServerConnection(arg1:string):Promise<Record<string, any>>;

export function UpsertPortForward(arg1:config.PortForward):Promise<void>;

export function UpsertServer(arg1:config.Server):Promise<void>;

export function UpsertSyncMapping(arg1:config.SyncMapping):Promise<void>;
