// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteManagedProcess(arg1) {
  return window['go']['main']['App']['DeleteManagedProcess'](arg1);
}

export function DeletePortForward(arg1) {
  return window['go']['main']['App']['DeletePortForward'](arg1);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function DeleteSyncMapping(arg1) {
  return window['go']['main']['App']['DeleteSyncMapping'](arg1);
}

export function ExportConfig(arg1) {
  return window['go']['main']['App']['ExportConfig'](arg1);
}

export function GetLanguage() {
  return window['go']['main']['App']['GetLanguage']();
}

export function GetLaunchAtLogin() {
  return window['go']['main']['App']['GetLaunchAtLogin']();
}

export function GetSyncBackend() {
  return window['go']['main']['App']['GetSyncBackend']();
}

export function GetTheme() {
  return window['go']['main']['App']['GetTheme']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ImportConfig(arg1, arg2) {
  return window['go']['main']['App']['ImportConfig'](arg1, arg2);
}

export function ListManagedProcesses() {
  return window['go']['main']['App']['ListManagedProcesses']();
}

export function ListPortForwards() {
  return window['go']['main']['App']['ListPortForwards']();
}

export function ListServers() {
  return window['go']['main']['App']['ListServers']();
}

export function ListSyncMappings() {
  return window['go']['main']['App']['ListSyncMappings']();
}

export function ManagedProcessStatus(arg1) {
  return window['go']['main']['App']['ManagedProcessStatus'](arg1);
}

export function OpenConfigDirectory() {
  return window['go']['main']['App']['OpenConfigDirectory']();
}

export function OpenLogDirectory() {
  return window['go']['main']['App']['OpenLogDirectory']();
}

export function PortForwardStatus(arg1) {
  return window['go']['main']['App']['PortForwardStatus'](arg1);
}

export function RecentLogs() {
  return window['go']['main']['App']['RecentLogs']();
}

export function RunFullSync(arg1) {
  return window['go']['main']['App']['RunFullSync'](arg1);
}

export function SelectLocalDirectory(arg1) {
  return window['go']['main']['App']['SelectLocalDirectory'](arg1);
}

export function SetLanguage(arg1) {
  return window['go']['main']['App']['SetLanguage'](arg1);
}

export function SetLaunchAtLogin(arg1) {
  return window['go']['main']['App']['SetLaunchAtLogin'](arg1);
}

export function SetSyncBackend(arg1) {
  return window['go']['main']['App']['SetSyncBackend'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function StartManagedProcess(arg1) {
  return window['go']['main']['App']['StartManagedProcess'](arg1);
}

export function StartPortForward(arg1) {
  return window['go']['main']['App']['StartPortForward'](arg1);
}

export function StopManagedProcess(arg1) {
  return window['go']['main']['App']['StopManagedProcess'](arg1);
}

export function StopPortForward(arg1) {
  return window['go']['main']['App']['StopPortForward'](arg1);
}

export function TestServerConnection(arg1) {
  return window['go']['main']['App']['TestServerConnection'](arg1);
}

export function UpsertManagedProcess(arg1) {
  return window['go']['main']['App']['UpsertManagedProcess'](arg1);
}

export function UpsertPortForward(arg1) {
  return window['go']['main']['App']['UpsertPortForward'](arg1);
}

export function UpsertServer(arg1) {
  return window['go']['main']['App']['UpsertServer'](arg1);
}

export function UpsertSyncMapping(arg1) {
  return window['go']['main']['App']['UpsertSyncMapping'](arg1);
}
